### ISSUE TITLE
does this work for oneplus ace 2

### ISSUE THREAD

**Issue by binaryslark** [OnePlusOSS/android_kernel_msm-5.10_oneplus_sm8450#5]
- oneplus ace 2 
- Android 13
- kernel version: 5.10.117

**Comment by OnePlusOSSAdmin** [comment]
You could get kernel code for OnePlue Ace 2 in the following links.  It's same with OnePlus 11R. Maybe we would push a seperate branch for Ace 2.
`https://github.com/OnePlusOSS/android_kernel_oneplus_sm8475/tree/oneplus_sm8475_t_13.0_oneplus_11R_5G
https://github.com/OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8475/tree/oneplus_sm8475_t_13.0_oneplus_11R_5G
`
